Update azure-pipelines-1.yml for Azure Pipelines

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -12,30 +12,27 @@ stages:
       vmImage: 'ubuntu-latest'
     steps:
     - script: |
-        # Install conftest using cURL
-        LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
-        wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
-        tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
-        sudo mv conftest /usr/local/bin
-
-
         # Print value of $(Build.SourcesDirectory)
         echo "Build.SourcesDirectory: $(Build.SourcesDirectory)"
 
         # Print directory contents
         ls -la $(Build.SourcesDirectory)
+        # Pull the OPA Docker image
+        docker pull openpolicyagent/opa:latest
 
-        # Run OPA policy scan using conftest
-         conftest test -p /data/OPA_policy.rego $(Build.SourcesDirectory)
+        # Run OPA against Terraform code using Docker
+        docker run --rm -v $(Build.SourcesDirectory):/data openpolicyagent/opa eval -d /data/OPA_policy.rego 'data.main'
 
-        # Capture the exit code of conftest
-        CONFTEST_EXIT_CODE=$?
+
+
+        # Capture the exit code of the OPA evaluation
+        OPA_EXIT_CODE=$?
 
         # Check the exit code and exit accordingly
-        if [ $CONFTEST_EXIT_CODE -eq 0 ]; then
+        if [ $OPA_EXIT_CODE -eq 0 ]; then
           echo "OPA scan passed successfully."
         else
           echo "OPA scan failed with policy violations."
         fi
-        exit $CONFTEST_EXIT_CODE
+        exit $OPA_EXIT_CODE
       displayName: 'Run OPA Scan'
